### ISSUE TITLE
Not able to load mod correctly

### ISSUE THREAD

**Issue by Adamih** [Jobus0/ObraDinn-AntiMotionSickness#1]
I seem to be unable to get the mod working correctly. I have unpacked the BepInEx (x86) .zip in the game directory, created the "Plugins" folder, and the config file is correctly generated. When I restart the game there is no FOV slider in the options, there is still bobbing, boat sway, etc. Also, there are now three "Sharp (shrink 1-3)", where they all seem to do the same thing as the regular Sharp (shrink) setting. 

I am running the GOG version of the game on the latest update (v1.2x) with the 2017 version of Unity.

Is there any way to debug what is going wrong? 

(Btw, I made a duplicate comment on the Nexus page.)

**Comment by Adamih** [comment]
Update: FOV is apparently working. While the settings UI is strange, perhaps more fixes in the mod are also working as intended. I will be testing some more.

**Comment by Jobus0** [comment]
Please upload your BepInEx\LogOutput.log.

> When I restart the game there is no FOV slider in the options

Sorry, my description is misleading, the mod doesn't add an in-game option for FOV, it is only configurable from the generated config file (requiring restarts to take effect).

> Also, there are now three "Sharp (shrink 1-3)"

This mod should have no effect on those settings - or any other in-game settings. The different Sharp (Shrink) options are vanilla and are supposed to make the game viewport smaller. I think the number of shrink levels depends on your monitor resolution.

> While the settings UI is strange

Did you notice any more strangeness besides the Sharp (Shrink) options?

**Comment by Jobus0** [comment]
As for the ship swaying, to be clear, the mod only disables the swaying of the entire ship by the waves.

With the mod, the ropes and sails should still be swaying. And the water and clouds should still be moving. But the horizon should be static as a nearly perfect horizontal line. Does the horizon move up and down or rotate for you?

**Comment by Jobus0** [comment]
@Adamih Did you get the mod working as expected?

**Comment by Adamih** [comment]
After some playtime, everything seems to be working👍I assumed that the boat sway would be severely toned down. It is the case that the horizon sway is removed. I (for some unknown reason) read that a FOV-slider was included, which seems to not be the case on a second read, hence the confusion around the options screen. So everything seems to be working correctly after all! 

Sorry for the spook. Thank you so much for creating this mod! ❤️

**Comment by Jobus0** [comment]
Glad everything is in order! I wish you a wonderful playthrough void of any motion sickness then!
